{% set version = "0.10.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-performance
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/performance_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/performance/performance_{{ version }}.tar.gz
  sha256: 0b66d18829a6f09ff9692ffba2db3c9f12e39f5f1fdd2bcf0e74c0137c39dd97

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bayestestr >=0.12.0
    - r-datawizard >=0.5.1
    - r-insight >=0.18.3
  run:
    - r-base
    - r-bayestestr >=0.12.0
    - r-datawizard >=0.5.1
    - r-insight >=0.18.3

test:
  commands:
    - $R -e "library('performance')"           # [not win]
    - "\"%R%\" -e \"library('performance')\""  # [win]

about:
  home: https://easystats.github.io/performance/
  license: GPL-3.0-only
  summary: Utilities for computing measures to assess model quality, which are not directly provided by R's 'base' or 'stats' packages. These  include e.g. measures like r-squared, intraclass correlation coefficient (Nakagawa, Johnson & Schielzeth (2017) <doi:10.1098/rsif.2017.0213>),  root mean squared error or functions
    to check models for overdispersion,  singularity or zero-inflation and more. Functions apply to a large variety of regression models, including generalized linear models, mixed effects models and Bayesian models.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
